---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project containing nginx-apache-grafana-prometheus-loki services
  sourceRepos:
    - git@github.com:yogrr/study-playsdev-k8s.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: nginx-apache
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
