---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-grafana
  namespace: monitoring
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/grafana/
