---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-auth-update-htpasswd
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: updater
              image: illusior/nginx-apache:yc-nginx-secret-updater
              command: ["/bin/sh", "-c"]
              args:
                - |
                  . /scripts/yc-update-htpasswd.sh
              volumeMounts:
                - name: shared-volume
                  mountPath: /etc/nginx/keys/.htpasswd
                  subPath: .htpasswd
          volumes:
            - name: shared-volume
              persistentVolumeClaim:
                claimName: nginx-auth
          restartPolicy: OnFailure
