---
apiVersion: v1
kind: Service
metadata:
  name: nginx-auth
  namespace: nginx-auth
spec:
  type: NodePort
  selector:
    app: nginx-auth
  ports:
    - port: 80
      targetPort: ng-http
      name: http-nginx-port
      nodePort: 30090
