---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-auth
  namespace: nginx-auth
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-nginx-auth
  hostPath:
    path: /data/nginx-auth/
