---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-auth
  namespace: nginx-auth
  labels:
    app: nginx-auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: local-storage-nginx-auth
  volumeMode: Filesystem
