---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: nginx-apache
spec:
  type: ClusterIP
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: apache-port
      name: http-apache-clusterip-port
