---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  namespace: nginx-apache
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: ng-http
      name: http-nginx-port
      nodePort: 30080
    - port: 443
      targetPort: ng-https
      name: https-nginx-port
      nodePort: 30081
