---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ci
  namespace: nginx-apache
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: ng-http
      name: http-nginx-ci
    - protocol: TCP
      port: 443
      targetPort: ng-https
      name: https-nginx-ci
