---
apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
  {{- with .Values.loadbalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.loadbalancer.externalIp }}
  ports:
    - name: lb-nginx-http
      port: 80
    - name: lb-nginx-https
      port: 443
  selector:
    app: nginx
